from __future__ import annotations

from typing import Final, overload

class timedelta:
    def __new__(
        cls,
        days: int = 0,
        seconds: int = 0,
        microseconds: int = 0,
        milliseconds: int = 0,
        minutes: int = 0,
        hours: int = 0,
        weeks: int = 0,
    ) -> timedelta: ...
    @property
    def days(self) -> int: ...
    @property
    def seconds(self) -> int: ...
    @property
    def microseconds(self) -> int: ...
    def total_seconds(self) -> float: ...
    def __add__(self, other: timedelta, /) -> timedelta: ...
    def __sub__(self, other: timedelta, /) -> timedelta: ...
    def __neg__(self) -> timedelta: ...

class tzinfo: ...

class timezone(tzinfo):
    utc: Final[timezone]
    def __new__(cls, offset: timedelta, name: str | None = None) -> timezone: ...

class date:
    def __new__(cls, year: int, month: int, day: int) -> date: ...
    @classmethod
    def today(cls) -> date: ...
    def __add__(self, other: timedelta, /) -> date: ...
    @overload
    def __sub__(self, other: date, /) -> timedelta: ...
    @overload
    def __sub__(self, other: timedelta, /) -> date: ...

class datetime(date):
    def __new__(
        cls,
        year: int,
        month: int,
        day: int,
        hour: int = 0,
        minute: int = 0,
        second: int = 0,
        microsecond: int = 0,
        tzinfo: timezone | None = None,
    ) -> datetime: ...
    @classmethod
    def now(cls, tz: timezone | None = None) -> datetime: ...
    @property
    def tzinfo(self) -> timezone | None: ...
    def __add__(self, other: timedelta, /) -> datetime: ...
    @overload
    def __sub__(self, other: datetime, /) -> timedelta: ...
    @overload
    def __sub__(self, other: timedelta, /) -> datetime: ...
